# Data Cleaning and Preprocessing with Pandas

Data cleaning is a crucial step in the data science workflow. In this tutorial, we'll learn how to handle missing values, deal with outliers, and convert categorical data to one-hot encoded data using pandas.

First, we import the necessary libraries.

In [4]:
import pandas as pd
import numpy as np
import warnings
warnings.simplefilter('ignore')

## Sample Data

We'll create a sample DataFrame to work with:

In [2]:
# Sample data
data = {
    'Age': [25, 27, 29, None, 23, np.nan, 30],
    'Salary': [50000, 54000, 50000, 45000, None, 52000, 58000],
    'Gender': ['Male', 'Female', 'Female', 'Male', 'Female', 'Male', None],
    'Department': ['IT', 'HR', 'HR', 'IT', 'HR', 'IT', 'Finance']
}

df = pd.DataFrame(data)
df

    Age   Salary  Gender Department
0  25.0  50000.0    Male         IT
1  27.0  54000.0  Female         HR
2  29.0  50000.0  Female         HR
3   NaN  45000.0    Male         IT
4  23.0      NaN  Female         HR
5   NaN  52000.0    Male         IT
6  30.0  58000.0    None    Finance

## Imputing Missing Values

Missing values can be imputed in various ways depending on the nature of the data and the missingness.

### Numeric Columns

For numeric columns like 'Age' and 'Salary', we can impute missing values with the mean or median:

In [5]:
# Fill missing values for 'Age' with the mean
df['Age'].fillna(df['Age'].mean(), inplace=True)

# Fill missing values for 'Salary' with the median
df['Salary'].fillna(df['Salary'].median(), inplace=True)
df

    Age   Salary  Gender Department
0  25.0  50000.0    Male         IT
1  27.0  54000.0  Female         HR
2  29.0  50000.0  Female         HR
3  26.8  45000.0    Male         IT
4  23.0  51000.0  Female         HR
5  26.8  52000.0    Male         IT
6  30.0  58000.0    None    Finance

### Categorical Columns

For categorical columns, we can impute missing values with the mode (the most frequent value):

In [4]:
# Fill missing values for 'Gender' with the mode
df['Gender'].fillna(df['Gender'].mode()[0], inplace=True)

# For simplicity, let's assume 'Department' has no missing values
df

    Age   Salary  Gender Department
0  25.0  50000.0    Male         IT
1  27.0  54000.0  Female         HR
2  29.0  50000.0  Female         HR
3  26.8  45000.0    Male         IT
4  23.0  51000.0  Female         HR
5  26.8  52000.0    Male         IT
6  30.0  58000.0  Female    Finance

## Dealing with Outliers

Outliers can skew your data and affect the outcome of your analysis. Here's a simple method to detect and remove outliers based on the Z-score:

In [5]:
from scipy import stats

# Calculate Z-scores of 'Age' and 'Salary'
z_scores = stats.zscore(df[['Age', 'Salary']])

# Define a threshold
threshold = 3

# Find where the absolute Z-scores are less than the threshold
without_outliers = (np.abs(z_scores) < threshold).all(axis=1)

# Filter the dataframe
df_cleaned = df[without_outliers]
df_cleaned

    Age   Salary  Gender Department
0  25.0  50000.0    Male         IT
1  27.0  54000.0  Female         HR
2  29.0  50000.0  Female         HR
3  26.8  45000.0    Male         IT
4  23.0  51000.0  Female         HR
5  26.8  52000.0    Male         IT
6  30.0  58000.0  Female    Finance

## Converting Categorical Data to One-Hot Encoded Data

One-hot encoding is a process by which categorical variables are converted into a form that could be provided to ML algorithms to do a better job in prediction.

In [6]:
# One-hot encode 'Gender' and 'Department' columns
df_encoded = pd.get_dummies(df_cleaned, columns=['Gender', 'Department'])
df_encoded

,Age,Salary,Gender_Female,Gender_Male,Department_Finance,Department_HR,Department_IT
0,25.0,50000.0,0,1,0,0,1
1,27.0,54000.0,1,0,0,1,0
2,29.0,50000.0,1,0,0,1,0
3,26.8,45000.0,0,1,0,0,1
4,23.0,51000.0,1,0,0,1,0
5,26.8,52000.0,0,1,0,0,1
6,30.0,58000.0,1,0,1,0,0

## Conclusion

In this tutorial, we covered basic data cleaning and preprocessing steps using pandas. These steps are crucial for preparing your data for further analysis or machine learning models. Always remember to explore your data and understand its characteristics before applying any cleaning or preprocessing techniques.