# Dictionaries & Pandas
- Execute the follow cell to make the st_to dictionary.

In [1]:
#Creating dictionary from columns in dataframe
import pandas as pd
storedata = pd.read_csv('storedata_clean.csv',sep=";")

store_id = storedata['Store ID'].values.tolist()
turnover = storedata['Profit'].values.tolist()
floor = storedata['Floor Space'].values.tolist()

st_to = dict(zip(store_id, turnover))

### 1.1 Print dictionary
St_to contains the storenumbers (store id) and the turnover of each store.
- Print st_to.

{1437: 3410865,
 1544: 4034051,
 2039: 2297810,
 2055: 2398990,
 2141: 2288235,
 2309: 3058134,
 3800: 2793160,
 4214: 3345936,
 4857: 3117205,
 4860: 3153278,
 7491: 3056804,
 7566: 1801619,
 8207: 3797953,
 9171: 3138911,
 11440: 2724068,
 13132: 2382751,
 13984: 3321899,
 14359: 2803867,
 14421: 3640627,
 14984: 3075352,
 15125: 3491993,
 16727: 3252148,
 16741: 3041618,
 18554: 3737466,
 19296: 4217291,
 20304: 2008363,
 20971: 3516397,
 21359: 3957233,
 23025: 2942839,
 23231: 2242288,
 23249: 2616387,
 23705: 2493975,
 24174: 2203994,
 24618: 2458785,
 24737: 4253984,
 26307: 4185306,
 29319: 4160531,
 32610: 3100521,
 34686: 3246954,
 35207: 2085733,
 35944: 3741911,
 36979: 2506748,
 37708: 2393869,
 37916: 4137224,
 40352: 3572475,
 40676: 3121837,
 41475: 2799074,
 42172: 2707402,
 42797: 4176642,
 42943: 1829621,
 43044: 2681110,
 43066: 2411437,
 44476: 4300537,
 44722: 3758014,
 45223: 2234201,
 45547: 2342229,
 45577: 2104028,
 46116: 2406120,
 47290: 2839607,
 48341: 2831103,
 50703: 3032277,
 51992: 3625088,
 52414: 2196757,
 54193: 3336417,
 55138: 2779994,
 55717: 3175101,
 55895: 4587304,
 55967: 3029751,
 56056: 1512452,
 56595: 3418735,
 56930: 2526616,
 57418: 2333940,
 58249: 3197934,
 58882: 3135133,
 59280: 3822904,
 59431: 2538362,
 59517: 1855427,
 59653: 2260838,
 59794: 3524409,
 60116: 3709026,
 61950: 3337861,
 62022: 2407898,
 62586: 3260276,
 63017: 1792809,
 64781: 2804353,
 65437: 2869330,
 65659: 2422936,
 66482: 4237135,
 66844: 3007050,
 67041: 4018966,
 67403: 2553461,
 67717: 3817558,
 67825: 2405770,
 67831: 1764019,
 68816: 4793593,
 69540: 2896362,
 73474: 3192066,
 74421: 3092180,
 74620: 2419983,
 74958: 2701564,
 76653: 3606536,
 76773: 3304795,
 77163: 3663843,
 77644: 3965957,
 78305: 2651301,
 78368: 3487542,
 78904: 2004312,
 79413: 3102538,
 81258: 2291029,
 82709: 3895318,
 82754: 3741407,
 83250: 2604575,
 83312: 1648919,
 83479: 1665527,
 83480: 3654694,
 84225: 3598894,
 85185: 2172265,
 85476: 2397407,
 87212: 2329927,
 87510: 3444876,
 88442: 2564358,
 88942: 2534145,
 90621: 2956061,
 90995: 2467943,
 91085: 3891535,
 92341: 3498966,
 92768: 2872001,
 93212: 3501093,
 93991: 3774401,
 95915: 3584813,
 96852: 2561019,
 96853: 2581954,
 96858: 2589339,
 98062: 2583755,
 98923: 950924,
 99854: 3485295}

## 2 Single dictionaries
Assignments:

- Print the turnover of store 13132
- Add store 99999 with turnover of 3100000
- Print the turnover of 99999
- Update turnover of the new store to 3200000 and print the turnover
- Delete store 99999 and check if this deletion succeeded by attempting to print its turnover again

In [7]:
#print turnover of store 13132


#Add store 99999 with turnover of 3100000. Print the turnover


#Update turnover of the new store to 3200000 and print the turnover


#delete the new store and check deletion by attempting to print it again

2382751
3100000
3200000

KeyError: 99999

## 3 Nested dictionaries
- Execute the following cell to make the dictionary st_to_fl.

In [8]:
#Creating a nested dictionary
st_to_fl = dict(map(lambda x, y, z : (x, {"turnover":y , "floor":z}), store_id, turnover, floor))

- Print st_to_fl and study the structure of this 'nested' dictionary.

In [9]:
#Get an understanding of the structure of the dictionary

{1437: {'turnover': 3410865, 'floor': 18526},
 1544: {'turnover': 4034051, 'floor': 18569},
 2039: {'turnover': 2297810, 'floor': 12288},
 2055: {'turnover': 2398990, 'floor': 17092},
 2141: {'turnover': 2288235, 'floor': 11307},
 2309: {'turnover': 3058134, 'floor': 17888},
 3800: {'turnover': 2793160, 'floor': 13814},
 4214: {'turnover': 3345936, 'floor': 15643},
 4857: {'turnover': 3117205, 'floor': 13869},
 4860: {'turnover': 3153278, 'floor': 12071},
 7491: {'turnover': 3056804, 'floor': 13487},
 7566: {'turnover': 1801619, 'floor': 11071},
 8207: {'turnover': 3797953, 'floor': 18923},
 9171: {'turnover': 3138911, 'floor': 13827},
 11440: {'turnover': 2724068, 'floor': 14588},
 13132: {'turnover': 2382751, 'floor': 11824},
 13984: {'turnover': 3321899, 'floor': 14291},
 14359: {'turnover': 2803867, 'floor': 10911},
 14421: {'turnover': 3640627, 'floor': 15219},
 14984: {'turnover': 3075352, 'floor': 12128},
 15125: {'turnover': 3491993, 'floor': 18686},
 16727: {'turnover': 3252148, 'floor': 19025},
 16741: {'turnover': 3041618, 'floor': 18535},
 18554: {'turnover': 3737466, 'floor': 16219},
 19296: {'turnover': 4217291, 'floor': 19337},
 20304: {'turnover': 2008363, 'floor': 12234},
 20971: {'turnover': 3516397, 'floor': 13810},
 21359: {'turnover': 3957233, 'floor': 19000},
 23025: {'turnover': 2942839, 'floor': 16736},
 23231: {'turnover': 2242288, 'floor': 12959},
 23249: {'turnover': 2616387, 'floor': 16607},
 23705: {'turnover': 2493975, 'floor': 18284},
 24174: {'turnover': 2203994, 'floor': 18399},
 24618: {'turnover': 2458785, 'floor': 18077},
 24737: {'turnover': 4253984, 'floor': 19093},
 26307: {'turnover': 4185306, 'floor': 16915},
 29319: {'turnover': 4160531, 'floor': 14605},
 32610: {'turnover': 3100521, 'floor': 11834},
 34686: {'turnover': 3246954, 'floor': 15041},
 35207: {'turnover': 2085733, 'floor': 13127},
 35944: {'turnover': 3741911, 'floor': 17586},
 36979: {'turnover': 2506748, 'floor': 12075},
 37708: {'turnover': 2393869, 'floor': 11441},
 37916: {'turnover': 4137224, 'floor': 17006},
 40352: {'turnover': 3572475, 'floor': 12913},
 40676: {'turnover': 3121837, 'floor': 14948},
 41475: {'turnover': 2799074, 'floor': 11572},
 42172: {'turnover': 2707402, 'floor': 11038},
 42797: {'turnover': 4176642, 'floor': 18143},
 42943: {'turnover': 1829621, 'floor': 14359},
 43044: {'turnover': 2681110, 'floor': 13289},
 43066: {'turnover': 2411437, 'floor': 10774},
 44476: {'turnover': 4300537, 'floor': 13637},
 44722: {'turnover': 3758014, 'floor': 15053},
 45223: {'turnover': 2234201, 'floor': 10944},
 45547: {'turnover': 2342229, 'floor': 11538},
 45577: {'turnover': 2104028, 'floor': 11898},
 46116: {'turnover': 2406120, 'floor': 13532},
 47290: {'turnover': 2839607, 'floor': 11967},
 48341: {'turnover': 2831103, 'floor': 16270},
 50703: {'turnover': 3032277, 'floor': 12604},
 51992: {'turnover': 3625088, 'floor': 19087},
 52414: {'turnover': 2196757, 'floor': 16055},
 54193: {'turnover': 3336417, 'floor': 14362},
 55138: {'turnover': 2779994, 'floor': 12363},
 55717: {'turnover': 3175101, 'floor': 15292},
 55895: {'turnover': 4587304, 'floor': 19295},
 55967: {'turnover': 3029751, 'floor': 14833},
 56056: {'turnover': 1512452, 'floor': 13709},
 56595: {'turnover': 3418735, 'floor': 16848},
 56930: {'turnover': 2526616, 'floor': 13899},
 57418: {'turnover': 2333940, 'floor': 15876},
 58249: {'turnover': 3197934, 'floor': 13008},
 58882: {'turnover': 3135133, 'floor': 13989},
 59280: {'turnover': 3822904, 'floor': 15220},
 59431: {'turnover': 2538362, 'floor': 12545},
 59517: {'turnover': 1855427, 'floor': 10072},
 59653: {'turnover': 2260838, 'floor': 18752},
 59794: {'turnover': 3524409, 'floor': 14246},
 60116: {'turnover': 3709026, 'floor': 12092},
 61950: {'turnover': 3337861, 'floor': 15409},
 62022: {'turnover': 2407898, 'floor': 10486},
 62586: {'turnover': 3260276, 'floor': 12856},
 63017: {'turnover': 1792809, 'floor': 16652},
 64781: {'turnover': 2804353, 'floor': 13283},
 65437: {'turnover': 2869330, 'floor': 14497},
 65659: {'turnover': 2422936, 'floor': 10804},
 66482: {'turnover': 4237135, 'floor': 19784},
 66844: {'turnover': 3007050, 'floor': 17912},
 67041: {'turnover': 4018966, 'floor': 17303},
 67403: {'turnover': 2553461, 'floor': 12987},
 67717: {'turnover': 3817558, 'floor': 19174},
 67825: {'turnover': 2405770, 'floor': 13635},
 67831: {'turnover': 1764019, 'floor': 19110},
 68816: {'turnover': 4793593, 'floor': 18503},
 69540: {'turnover': 2896362, 'floor': 13766},
 73474: {'turnover': 3192066, 'floor': 17531},
 74421: {'turnover': 3092180, 'floor': 16344},
 74620: {'turnover': 2419983, 'floor': 17982},
 74958: {'turnover': 2701564, 'floor': 19579},
 76653: {'turnover': 3606536, 'floor': 11992},
 76773: {'turnover': 3304795, 'floor': 10899},
 77163: {'turnover': 3663843, 'floor': 19223},
 77644: {'turnover': 3965957, 'floor': 17242},
 78305: {'turnover': 2651301, 'floor': 13009},
 78368: {'turnover': 3487542, 'floor': 15738},
 78904: {'turnover': 2004312, 'floor': 11198},
 79413: {'turnover': 3102538, 'floor': 16091},
 81258: {'turnover': 2291029, 'floor': 15785},
 82709: {'turnover': 3895318, 'floor': 17744},
 82754: {'turnover': 3741407, 'floor': 14466},
 83250: {'turnover': 2604575, 'floor': 19375},
 83312: {'turnover': 1648919, 'floor': 19587},
 83479: {'turnover': 1665527, 'floor': 18928},
 83480: {'turnover': 3654694, 'floor': 14304},
 84225: {'turnover': 3598894, 'floor': 19869},
 85185: {'turnover': 2172265, 'floor': 15763},
 85476: {'turnover': 2397407, 'floor': 19037},
 87212: {'turnover': 2329927, 'floor': 11901},
 87510: {'turnover': 3444876, 'floor': 13532},
 88442: {'turnover': 2564358, 'floor': 14087},
 88942: {'turnover': 2534145, 'floor': 11889},
 90621: {'turnover': 2956061, 'floor': 18496},
 90995: {'turnover': 2467943, 'floor': 17582},
 91085: {'turnover': 3891535, 'floor': 17521},
 92341: {'turnover': 3498966, 'floor': 16280},
 92768: {'turnover': 2872001, 'floor': 14962},
 93212: {'turnover': 3501093, 'floor': 11820},
 93991: {'turnover': 3774401, 'floor': 13908},
 95915: {'turnover': 3584813, 'floor': 10080},
 96852: {'turnover': 2561019, 'floor': 11884},
 96853: {'turnover': 2581954, 'floor': 14120},
 96858: {'turnover': 2589339, 'floor': 11205},
 98062: {'turnover': 2583755, 'floor': 16190},
 98923: {'turnover': 950924, 'floor': 15516},
 99854: {'turnover': 3485295, 'floor': 14468}}

- Print the floorspace of 13132.
- Add the new store 99999 to the dictionary with a turnover of 3100000 and floor space of 15000.
- Print the floor space and turnover of this new store.
- Change the turnover of 99999 in 3200000.
- Print the turnover of the new store.

In [12]:
#print floorspace of 13132

#add new store 99999 to the dictionary with turnover of 3100000 and floor space of 15000

#Change turnover into 3200000

11824
{'turnover': 3100000, 'floor': 15000}
{'turnover': 3200000, 'floor': 15000}

### 4  Pandas: reading a csv file
Study the following link:

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html

- Load storedata_clean.csv as the storedata dataframe. Take the following into account:
    - The delimiter of this file is a semicolon (;).
    - The index column of the new file is supposed to be "Store ID".
    
- Print the dataframe.

In [18]:
import pandas as pd
import numpy as np

,Town,Country,Manager name,Staff,Floor Space,Window,Car park,Demographic score,Location,40min population,30 min population,20 min population,10 min population,Store age,Clearance space,Competition number,Competition score,Profit,Performance
Store ID,,,,,,,,,,,,,,,,,,,
1437,Swinton (Greater Manchester),UK,Roger,9,18526,121,Yes,10,Retail Park,1288374,1138224,1006986,1002340,3,238,16,16,3410865,Good
1544,Stamford,UK,Ella,8,18569,121,Yes,11,Shopping Centre,1086225,1015321,1012182,1008436,4,384,15,19,4034051,Excellent
2039,Skipton,UK,Valentina,2,12288,105,No,12,Retail Park,1595638,1281661,1104490,1011395,11,219,13,18,2297810,Poor
2055,Stratton,UK,Antonia,7,17092,117,No,14,High Street,1179395,1022959,1009496,1002169,5,261,15,12,2398990,Poor
2141,Shepperton,UK,Gabriel,7,11307,103,No,18,Retail Park,1398558,1085170,1003137,1002513,7,200,19,13,2288235,Poor
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96853,South Benfleet,UK,Vitória,7,14120,110,Yes,13,Retail Park,1665074,1240813,1141898,1041041,6,202,18,14,2581954,Reasonable
96858,Sandy,UK,Matías,6,11205,103,No,15,Shopping Centre,1657769,1424404,1378708,1160929,5,203,13,18,2589339,Reasonable
98062,Sheerness,UK,Gustavo,7,16190,115,No,19,Shopping Centre,1407456,1359511,1200486,1063718,7,341,18,18,2583755,Reasonable
98923,Salford,UK,Rafael,6,15516,113,No,17,High Street,1451087,1245725,1127276,1045154,11,261,14,10,950924,Poor
99854,Stapleford,UK,Lea,9,14468,111,Yes,18,High Street,1706344,1307752,1159859,1020940,8,276,18,13,3485295,Good

### 5 Selecteren, loc and iloc
- Make the following assignments, as stated in the comments of the following cells:

In [19]:
# Print the 'Town' column as a Pandas Series. Print the type of this column.

Store ID
1437      Swinton (Greater Manchester)
1544                          Stamford
2039                           Skipton
2055                          Stratton
2141                        Shepperton
                     ...
96853                   South Benfleet
96858                            Sandy
98062                        Sheerness
98923                          Salford
99854                       Stapleford
Name: Town, Length: 136, dtype: object

In [ ]:
# Print the 'Town' column and the 'Staff' column as a Pandas DataFrame. Print the type.

Town     object
Staff     int64
dtype: object

                                   Town  Staff
Store ID
1437       Swinton (Greater Manchester)      9
1544                           Stamford      8
2039                            Skipton      2
2055                           Stratton      7
2141                         Shepperton      7
...                                 ...    ...
96853                    South Benfleet      7
96858                             Sandy      6
98062                         Sheerness      7
98923                           Salford      6
99854                        Stapleford      9

[136 rows x 2 columns]

In [ ]:
#Print the 5th, 6th and 7th observation (row) from storedata.

,Town,Country,Manager name,Staff,Floor Space,Window,Car park,Demographic score,Location,40min population,30 min population,20 min population,10 min population,Store age,Clearance space,Competition number,Competition score,Profit,Performance
Store ID,,,,,,,,,,,,,,,,,,,
2141,Shepperton,UK,Gabriel,7,11307,103,No,18,Retail Park,1398558,1085170,1003137,1002513,7,200,19,13,2288235,Poor
2309,Southwell,UK,Sarah,7,17888,119,Yes,19,Retail Park,1614716,1325848,1220059,1193318,2,394,17,11,3058134,Good
3800,Swinton (South Yorkshire),UK,James,8,13814,109,Yes,17,High Street,1323396,1047485,1000888,1000844,5,228,11,14,2793160,Reasonable

In [26]:
#Print the row of store (Store ID) 7566 as a Series. Use the loc method.

Town                      Staines
Country                        UK
Manager name               Olivia
Staff                           8
Floor Space                 11071
Window                        102
Car park                       No
Demographic score              12
Location              Retail Park
40min population          1514670
30 min population         1400857
20 min population         1319646
10 min population         1010879
Store age                      11
Clearance space               202
Competition number             15
Competition score              10
Profit                    1801619
Performance                  Poor
Name: 7566, dtype: object

In [27]:
#Print the rows of stores 99854 and 96858 as a dataframe. Use the loc method.

,Town,Country,Manager name,Staff,Floor Space,Window,Car park,Demographic score,Location,40min population,30 min population,20 min population,10 min population,Store age,Clearance space,Competition number,Competition score,Profit,Performance
Store ID,,,,,,,,,,,,,,,,,,,
99854,Stapleford,UK,Lea,9,14468,111,Yes,18,High Street,1706344,1307752,1159859,1020940,8,276,18,13,3485295,Good
96858,Sandy,UK,Matías,6,11205,103,No,15,Shopping Centre,1657769,1424404,1378708,1160929,5,203,13,18,2589339,Reasonable

In [28]:
#Print the rown and the staff of stores 81258 en 82709. Use the loc method.

                      Town  Staff
Store ID
81258           Shrewsbury      7
82709      South Petherton      6

In [29]:
#Print the Town, Manager and Staff columns, using the iloc method.

<class 'pandas.core.frame.DataFrame'>
Index: 136 entries, 1437 to 99854
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Town                136 non-null    object
 1   Country             136 non-null    object
 2   Manager name        136 non-null    object
 3   Staff               136 non-null    int64
 4   Floor Space         136 non-null    int64
 5   Window              136 non-null    int64
 6   Car park            136 non-null    object
 7   Demographic score   136 non-null    int64
 8   Location            136 non-null    object
 9   40min population    136 non-null    int64
 10  30 min population   136 non-null    int64
 11  20 min population   136 non-null    int64
 12  10 min population   136 non-null    int64
 13  Store age           136 non-null    int64
 14  Clearance space     136 non-null    int64
 15  Competition number  136 non-null    int64
 16  Competition score   136 non-null    int64
 17  Profit              136 non-null    int64
 18  Performance         136 non-null    object
dtypes: int64(13), object(6)
memory usage: 25.3+ KB